### ISSUE TITLE
crafty in arena 3.5.1

### ISSUE THREAD

**Issue by gpaunica** [MichaelB7/Crafty#4]
Hello,
I like Crafty chess engine verry much. I have created a tournament between Crafty 25.2 and Junior 13.3 in Arena 3.5.1 chess GUI, and there is a problem: when I start the tournament Crafty worked fine, but in the second game when sides have switched after white (Junior 13.3) made the first move Crafty instead to think and play like in the first game it displayed the message Engine 1 ilegal move! Please help me.
Thanks a lot.

**Comment by MichaelB7** [comment]
It would be helpful if you turn Arena and crafty logging on and submit log files.  I'm not familiar with Arena you would have to figure that out,  turn crafty logging on via the .rc file.

**Comment by toneewa** [comment]
That is probably from the removal of NewGame(), which I support being re-added.

**Comment by MichaelB7** [comment]
Crafty does not support new game by design.  For Arena, go to menu->engines->tournament, and in the dialogue that opens, click the tab "Start/Quit". The lowest check box, under "Engines", that is "restart engines after each game", and that has to be checked. I recommend an additional two second  "additional delay".  I recommend that setting for every engine, but that choice is yours.
